sbt/contraband

library/src/main/scala/ScalaCodeGen.scala, library/src/test/scala/ScalaCodeGenSpec.scala, library/src/test/scala/SchemaExample.scala
For instance for the following schema:
```json
{
"name": "simpleRecordExample",
"type": "record",
"target": "Scala",
"fields": [
{
"name": "foo",
"type": "type"
}
]
}
```
It will generate the following Scala code:
```scala
final class simpleRecordExample(
val foo: type)  {
override def equals(o: Any): Boolean = o match {
case x: simpleRecordExample => (this.foo == x.foo)
case _ => false
}
override def hashCode: Int = {
37 * (17 + foo.##)
}
override def toString: String = {
"simpleRecordExample(" + foo + ")"
}
private[this] def copy(foo: type = foo): simpleRecordExample = {
new simpleRecordExample(foo)
}
def withFoo(foo: type): simpleRecordExample = {
copy(foo = foo)
}
}
object simpleRecordExample {
def apply(foo: type): simpleRecordExample = new simpleRecordExample(foo)
}
```
=> Generate `withField` methods in Scala generator

LICENSE, build.sbt, project/plugins.sbt
~~I've merged the two previous subprojects (previously library and plugin) into only one project.~~
~~I've added the plugin and configuration to publish it to Bintray directly in `sbt/sbt-plugin-releases` repository.~~
~~**I've published this as v0.0.1 on Bintray.** Hope that's okay.~~
I've added a license (BSD 3 clauses, the same as sbt/sbt I think).
Both the plugin and the library are configured to be published in `sbt/sbt-plugin-release`
=> Publish to bintray

build.sbt
Otherwise the dependency from `plugin` to `library` won't be resolved.
I've released this as datatype-plugin and datatype 0.0.2 on bintray.
=> Declare `library` project as sbt plugin

library/src/main/scala/Indentation.scala, library/src/main/scala/JavaCodeGen.scala, library/src/main/scala/ScalaCodeGen.scala, library/src/main/scala/SchemaData.scala, library/src/test/scala/SchemaExample.scala, library/src/test/scala/SchemaSpec.scala
The Javadoc in the schema definition can now optionally span over
multiple lines. To write multiline Javadoc, it suffices to set the
property `doc` of any node to an array containing all the lines.
Single-line Javadoc can still be written using the previous style.
This will be useful when we will start to port other classes to sbt-datatype (e.g. `UpdateOptions`)
=> Support for multiline doc comment

library/src/main/scala/JavaCodeGen.scala, library/src/main/scala/ScalaCodeGen.scala, library/src/main/scala/SchemaData.scala, library/src/test/scala/CodeGenSpec.scala, library/src/test/scala/JavaCodeGenSpec.scala, library/src/test/scala/ScalaCodeGenSpec.scala, library/src/test/scala/SchemaExample.scala, library/src/test/scala/SchemaSpec.scala
It turns out that adding a new abstract method to an abstract class
doesn't break binary compatibility. The classes that extend the abstract
class will still be loaded correctly by even if they do not implement
some methods of their base class.
=> Generate abstract methods in protocols

library/src/main/scala/CodecCodeGen.scala, library/src/test/scala/CodecCodeGenSpec.scala, library/src/test/scala/SchemaExample.scala, plugin/src/main/scala/Plugin.scala, plugin/src/sbt-test/sbt-datatype/roundtrip-test/build.sbt, plugin/src/sbt-test/sbt-datatype/roundtrip-test/src/main/scala/com/example/Example.scala
1. Formats traits are capitalized.
2. What was called "full codec" (all formats traits) is now called a "protocol", and defaults to the name `CustomProtocol`. The build user can opt out of generating this by setting `None` to `datatypeProtocolName` setting. This usage of the term is consistent with sjson-new/sbinary.
3. `CustomProtocol` trait will inherit the formats traits instead of just listing them as self type.
4. The formats traits are topologically sorted so the most depended traits (such as `sjsonnew.BasicJsonProtocol`) would come last.
=> Full protocol improvements

library/src/main/scala/CodeGen.scala, library/src/main/scala/CodecCodeGen.scala, library/src/main/scala/JavaCodeGen.scala, library/src/main/scala/MixedCodeGen.scala, library/src/main/scala/ScalaCodeGen.scala, library/src/main/scala/SchemaData.scala, library/src/test/scala/CodeGenSpec.scala, library/src/test/scala/CodecCodeGenSpec.scala, library/src/test/scala/SchemaExample.scala, plugin/src/main/scala/Plugin.scala, plugin/src/sbt-test/sbt-datatype/roundtrip-test/build.sbt, plugin/src/sbt-test/sbt-datatype/roundtrip-test/src/main/datatype/greeting.json, plugin/src/sbt-test/sbt-datatype/roundtrip-test/src/main/scala/com/foo/Example.scala, plugin/src/sbt-test/sbt-datatype/roundtrip-test/src/main/scala/com/foo/FileFormats.scala, plugin/src/sbt-test/sbt-datatype/roundtrip-test/test
move codecNamespace to the schema file
Instead of specifying codecNamespace from the plugin, this moves the
specification to the schema file.
This allows each schema file to specify different package name.
In addition fully qualified names are used everywhere to fix bugs
around how formats are referenced.
- move fullCodec setting into schema
- rename datatypeScalaSealProtocols to datatypeScalaSealInterface
=> move some of the codec settings into schema file

library/src/main/scala/SchemaData.scala, library/src/test/scala/JavaCodeGenSpec.scala, library/src/test/scala/ScalaCodeGenSpec.scala, library/src/test/scala/SchemaExample.scala, library/src/test/scala/SchemaSpec.scala, notes/0.2.1.markdown, plugin/src/sbt-test/sbt-datatype/growable-schema-java/changes/person-2.json, plugin/src/sbt-test/sbt-datatype/growable-schema-scala/changes/person-2.json
Similar to Avro, enumeration is renamed to enum.
Symbol lists are renamed from types to symbols.
=> enum-related renaming

library/src/main/scala/JavaCodeGen.scala, library/src/main/scala/ScalaCodeGen.scala, library/src/main/scala/SchemaData.scala, library/src/test/scala/CodeGenSpec.scala, library/src/test/scala/CodecCodeGenSpec.scala, library/src/test/scala/JavaCodeGenSpec.scala, library/src/test/scala/ScalaCodeGenSpec.scala, library/src/test/scala/SchemaExample.scala, library/src/test/scala/SchemaSpec.scala, notes/0.2.1.markdown, plugin/src/sbt-test/sbt-datatype/growable-schema-java/changes/person-2.json, plugin/src/sbt-test/sbt-datatype/growable-schema-scala/changes/person-2.json
Avro calls the list of abstract methods "messages." I think it makes sense since we don't support the full methods.
=> "methods" is renamed to "messages"

build.sbt, library/src/main/scala/ScalaCodeGen.scala, library/src/test/scala/ScalaCodeGenSpec.scala, notes/0.2.3.markdown, plugin/src/sbt-test/sbt-datatype/simple-new-schema/src/main/datatype/schema.json
When the interface is empty, it was producing junk toString like this:
```
"nestedProtocol(" +  + ")"
```
=> Fixes code generation for `interface`'s `toString`.

library/src/main/scala/CodecCodeGen.scala, library/src/test/scala/CodecCodeGenSpec.scala, library/src/test/scala/SchemaExample.scala, notes/0.2.5.markdown, plugin/src/sbt-test/sbt-datatype/recursive-schema/build.sbt, plugin/src/sbt-test/sbt-datatype/recursive-schema/project/plugins.sbt, plugin/src/sbt-test/sbt-datatype/recursive-schema/src/main/datatype/recursive.json, plugin/src/sbt-test/sbt-datatype/recursive-schema/test
`Dag.topologicalSort` checks for cycles, but certain structures may
contain cycles and still be valid. We use `Dag.topologicalSortUnchecked`,
which doesn't checks for cycle (but still works with cyclic structures),
to order the required formats rather than `Dag.topologicalSort`.
See the attached scripted test for an example of legitimate cyclic structure.
=> Generate codec for recursive structures

library/src/main/scala/ScalaCodeGen.scala, library/src/test/scala/ScalaCodeGenSpec.scala, library/src/test/scala/SchemaExample.scala, notes/0.2.8/no-default-arguments.markdown
Fixes #48. Fixes #49.
Revert "Add support for public, overloaded, bincompat copy"
This reverts commit 3311302fb3d410d940a9a3384967c45c805eed1b.
Make the copy method protected[this] so it can be defined and uses in the parent
=> Remove public copy method.

library/src/main/scala/sbt/contraband/CodecCodeGen.scala, library/src/test/scala/JsonSchemaExample.scala
Fixes #61 
Here's how it's going to generate now.
Also added line breaks.
```scala
/**
* This code is generated using sbt-datatype.
*/
// DO NOT EDIT MANUALLY
package sbt.librarymanagement
trait LibraryManagementCodec extends
_root_.OptionFormats with
sjsonnew.BasicJsonProtocol with
sbt.librarymanagement.ConfigurationFormats with
_root_.MapFormats with
sbt.librarymanagement.ArtifactFormats with
_root_.SetFormats with
sbt.librarymanagement.ArtifactTypeFilterFormats with
sbt.librarymanagement.InclExclRuleFormats with
sbt.librarymanagement.DisabledFormats with
sbt.librarymanagement.BinaryFormats with
sbt.librarymanagement.FullFormats with
sbt.librarymanagement.CrossVersionFormats with
sbt.librarymanagement.ModuleIDFormats with
sbt.librarymanagement.CallerFormats with
scala.Tuple2Formats with …
```
=> Fix full codec generation

docs/03-json.md, docs/ja/03-json.md, library/src/main/scala/sbt/contraband/CodeGen.scala, library/src/main/scala/sbt/contraband/CodecCodeGen.scala, library/src/main/scala/sbt/contraband/ast/SchemaAst.scala, library/src/main/scala/sbt/contraband/parser/JsonParser.scala, library/src/test/scala/GraphQLCodecCodeGenSpec.scala, library/src/test/scala/GraphQLExample.scala, library/src/test/scala/JsonCodecCodeGenSpec.scala, library/src/test/scala/JsonSchemaExample.scala
This PR is on top of #62 and #63 
Fixes #55
Here's Contraband schema language:
```
interface MiddleInterface implements InterfaceExample
@generateCodec(false)
{
field: Int
}
```
Here's the JSON notation:
```json
{
"name": "MiddleInterface",
"target": "Scala",
"type": "interface",
"generateCodec": false,
"types": [ ]
}
```
=> Implement generateCodec annotation that lets you skip it

library/src/main/scala/sbt/contraband/CodecCodeGen.scala, library/src/main/scala/sbt/contraband/ScalaCodeGen.scala, library/src/test/scala/GraphQLExample.scala, library/src/test/scala/GraphQLScalaCodeGenSpec.scala, plugin/src/sbt-test/sbt-contraband/roundtrip-test-scala/src/main/contraband/map.contra
I noticed we have `Map[String, String]` in https://github.com/sbt/sbt/blob/367ab3b2d34655345bdb9ccac83a97f7b0140090/run/src/main/scala/sbt/Fork.scala#L30
=> Add StringStringMap

library/src/main/scala/sbt/contraband/CodecCodeGen.scala, library/src/main/scala/sbt/contraband/JavaCodeGen.scala, library/src/test/scala/GraphQLJavaCodeGenSpec.scala, library/src/test/scala/GraphQLMixedCodeGenSpec.scala, library/src/test/scala/JsonJavaCodeGenSpec.scala, library/src/test/scala/JsonSchemaExample.scala, plugin/src/sbt-test/sbt-contraband/roundtrip-test-java/src/main/scala/com/foo/Example.scala, plugin/src/sbt-test/sbt-contraband/roundtrip-test-mixed/src/main/scala/com/foo/Example.scala
Fixes https://github.com/sbt/zinc/issues/317
Java code will now generate static factory methods named "make":
```java
public final class TypeExample implements java.io.Serializable {
// Some extra code
public static TypeExample make(java.util.Optional<java.net.URL> _field) {
return new TypeExample(_field);
}
public static TypeExample make(java.net.URL _field) {
return new TypeExample(_field);
}
...
```
and the constructors are protected.
/cc @stuhood, @jvican
=> use static method make to create Java objects

library/src/main/scala/sbt/contraband/CodecCodeGen.scala, library/src/main/scala/sbt/contraband/JavaCodeGen.scala, library/src/test/scala/GraphQLJavaCodeGenSpec.scala, library/src/test/scala/JsonJavaCodeGenSpec.scala, library/src/test/scala/JsonSchemaExample.scala, plugin/src/sbt-test/sbt-contraband/roundtrip-test-java/src/main/scala/com/foo/Example.scala, plugin/src/sbt-test/sbt-contraband/roundtrip-test-mixed/src/main/scala/com/foo/Example.scala
In actual usage make stands out in Scala.
I wish we could use apply, but that doesn't work for static methods.
I am now generating both `create` and `of`. For most cases, I would prefer the `of`.
=> Change Java factory method name from make to create/of

library/src/main/scala/sbt/contraband/ScalaCodeGen.scala, library/src/test/scala/GCodeGenSpec.scala, library/src/test/scala/GraphQLMixedCodeGenSpec.scala, library/src/test/scala/GraphQLScalaCodeGenSpec.scala, library/src/test/scala/JsonScalaCodeGenSpec.scala, library/src/test/scala/JsonSchemaExample.scala
This ensures that the private constructors are generated, which in turn
ensures that new versions of contraband types are bincompat.
=> Change the apply overloads codegen to use the private constructors

library/src/main/scala/sbt/contraband/CodecCodeGen.scala
Tested locally with local changes in sbt/lm.
=> Honour the "generateCodec" directive when getting all the formats for a schema

library/src/main/scala/sbt/contraband/CodeGen.scala, library/src/main/scala/sbt/contraband/JavaCodeGen.scala, library/src/main/scala/sbt/contraband/ScalaCodeGen.scala, library/src/test/scala/GraphQLJavaCodeGenSpec.scala, library/src/test/scala/GraphQLMixedCodeGenSpec.scala, library/src/test/scala/JsonJavaCodeGenSpec.scala, plugin/src/sbt-test/sbt-contraband/roundtrip-test-java/src/main/contraband/greeting.contra, plugin/src/sbt-test/sbt-contraband/roundtrip-test-java/src/main/scala/com/foo/Example.scala, plugin/src/sbt-test/sbt-contraband/roundtrip-test-mixed/src/main/contraband/greeting.contra, plugin/src/sbt-test/sbt-contraband/roundtrip-test-mixed/src/main/scala/com/foo/Example.scala, plugin/src/sbt-test/sbt-contraband/roundtrip-test-scala/src/main/contraband/greeting.contra, plugin/src/sbt-test/sbt-contraband/roundtrip-test-scala/src/main/scala/com/foo/Example.scala
Fixes #119
1. Fixes equal/hashCode inconsistencies in Java.
2. Generate Array deep comparison code for Scala too since it does use Array when Java and Scala are mixed.
=> Fixes equal / hashCode inconsistencies

docs/02-code-generation.md, docs/ja/02-code-generation.md, library/src/main/scala/sbt/contraband/ScalaCodeGen.scala, library/src/test/scala/GraphQLMixedCodeGenSpec.scala, library/src/test/scala/GraphQLScalaCodeGenSpec.scala, library/src/test/scala/JsonScalaCodeGenSpec.scala, library/src/test/scala/JsonSchemaExample.scala
This reverts commit 76cd9a2219ec4c682fee99bafd4fa26285c7361a.
At the time I thought that these were required to migrate LM's data
types to Contraband. I was mistaken: I can use the generated "with*"
methods instead.
=> Revert "Make the copy method protected[this] so it can be defined and uses in the parent"

library/src/main/scala/sbt/contraband/CodeGen.scala, library/src/test/scala/JsonJavaCodeGenSpec.scala
`java.lang.<boxed type>` constructors deprecated since JDK9
=> use "valueOf" methods instead of deprecated constructors

plugin/src/main/scala/ContrabandPlugin.scala
Attempting to fix #137
I tried to do something similar in a local project and it seemed promising. I used:
```sbt
lazy val myProject = (project in file("myProject")).enablePlugins(ContrabandPlugin).settings(
inConfig(Compile)(Seq(
scalacOptions := Seq(),  // this avoids turning warnings to compiler errors
// This avoids the "not found: type Builder" errors in the compiled output
libraryDependencies ++= (generateContrabands / contrabandCodecsDependencies).value,
generateContrabands := {
val result = generateContrabands.value
val s = streams.value
(s.cacheDirectory / "gen-api").delete()
result
}
))
)
```
This produces two distinct `src_managed` directories with separate class files.
NOTE: I was having trouble getting the code to compile, but that was because my failed results were cached …
=> Cache generated output per Scala version

library/src/main/scala/sbt/contraband/CodeGen.scala, library/src/main/scala/sbt/contraband/CodecCodeGen.scala, library/src/main/scala/sbt/contraband/Indentation.scala, library/src/main/scala/sbt/contraband/JavaCodeGen.scala, library/src/main/scala/sbt/contraband/ScalaCodeGen.scala
having platform-dependent line endings makes contraband behave platform dependently. That's undesirable for reproducibility and problematic in cases where contraband output is part of some VCS where people on different platforms collaborate.
fixes #122
=> use \n for line endings

docs/02-code-generation.md, library/src/main/scala/sbt/contraband/ScalaCodeGen.scala, library/src/test/scala/GraphQLMixedCodeGenSpec.scala, library/src/test/scala/GraphQLScalaCodeGenSpec.scala, library/src/test/scala/JsonScalaCodeGenSpec.scala, library/src/test/scala/JsonSchemaExample.scala
improve runtime performance of equals method by testing for reference equality first.
=> implement reference equality for scala

plugin/src/main/scala/ContrabandPlugin.scala, plugin/src/main/scala/JsonCodecPlugin.scala, plugin/src/sbt-test/sbt-contraband/java-lazy/build.sbt, plugin/src/sbt-test/sbt-contraband/mixed-schema-2/build.sbt, plugin/src/sbt-test/sbt-contraband/mixed-schema/build.sbt, plugin/src/sbt-test/sbt-contraband/roundtrip-test-java/build.sbt, plugin/src/sbt-test/sbt-contraband/roundtrip-test-mixed/build.sbt, plugin/src/sbt-test/sbt-contraband/zinc/build.sbt
- https://github.com/sbt/sbt/commit/e6fec6b1db5f212a74bf5e3766b9b70f2d983f24
- https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
=> use slash syntax. avoid deprecated `in`
